spring:
  application:
    name: api
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db
    username: dbuser
    password: userpass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

server:
  port: 18082
  servlet:
    context-path: /${spring.application.name}

logging:
  level:
    jp.co.rakuten.ecommerce.api: debug
